# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEditInicio_1 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditInicio_1.setGeometry(QtCore.QRect(90, 20, 110, 22))
        self.dateEditInicio_1.setCalendarPopup(True)
        self.dateEditInicio_1.setObjectName("dateEditInicio_1")
        self.dateEditFim_1 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditFim_1.setGeometry(QtCore.QRect(210, 20, 110, 22))
        self.dateEditFim_1.setCalendarPopup(True)
        self.dateEditFim_1.setObjectName("dateEditFim_1")
        self.labelPeriodo_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelPeriodo_1.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPeriodo_1.setFont(font)
        self.labelPeriodo_1.setObjectName("labelPeriodo_1")
        self.pushButtonPesquisar_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPesquisar_1.setGeometry(QtCore.QRect(620, 20, 75, 23))
        self.pushButtonPesquisar_1.setObjectName("pushButtonPesquisar_1")
        self.tableWidgetComparativo_1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetComparativo_1.setGeometry(QtCore.QRect(10, 50, 680, 200))
        self.tableWidgetComparativo_1.setObjectName("tableWidgetComparativo_1")
        self.tableWidgetComparativo_1.setColumnCount(0)
        self.tableWidgetComparativo_1.setRowCount(0)
        self.dateEditFim_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditFim_2.setGeometry(QtCore.QRect(210, 270, 110, 22))
        self.dateEditFim_2.setCalendarPopup(True)
        self.dateEditFim_2.setObjectName("dateEditFim_2")
        self.dateEditInicio_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditInicio_2.setGeometry(QtCore.QRect(90, 270, 110, 22))
        self.dateEditInicio_2.setCalendarPopup(True)
        self.dateEditInicio_2.setObjectName("dateEditInicio_2")
        self.labelPeriodo_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelPeriodo_2.setGeometry(QtCore.QRect(10, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPeriodo_2.setFont(font)
        self.labelPeriodo_2.setObjectName("labelPeriodo_2")
        self.tableWidgetComparativo_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetComparativo_2.setGeometry(QtCore.QRect(10, 300, 680, 200))
        self.tableWidgetComparativo_2.setObjectName("tableWidgetComparativo_2")
        self.tableWidgetComparativo_2.setColumnCount(0)
        self.tableWidgetComparativo_2.setRowCount(0)
        self.pushButtonPesquisar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPesquisar_2.setGeometry(QtCore.QRect(620, 270, 75, 23))
        self.pushButtonPesquisar_2.setObjectName("pushButtonPesquisar_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Comparativo de Receitas"))
        self.labelPeriodo_1.setText(_translate("MainWindow", "Período 1:"))
        self.pushButtonPesquisar_1.setText(_translate("MainWindow", "PESQUISAR"))
        self.labelPeriodo_2.setText(_translate("MainWindow", "Período 2:"))
        self.pushButtonPesquisar_2.setText(_translate("MainWindow", "PESQUISAR"))
