# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEditAniversario = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditAniversario.setGeometry(QtCore.QRect(160, 20, 110, 22))
        self.dateEditAniversario.setCalendarPopup(True)
        self.dateEditAniversario.setObjectName("dateEditAniversario")
        self.labelData = QtWidgets.QLabel(self.centralwidget)
        self.labelData.setGeometry(QtCore.QRect(10, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelData.setFont(font)
        self.labelData.setObjectName("labelData")
        self.pushButtonPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPesquisar.setGeometry(QtCore.QRect(760, 20, 75, 23))
        self.pushButtonPesquisar.setObjectName("pushButtonPesquisar")
        self.tableWidgetAniversariantes = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetAniversariantes.setGeometry(QtCore.QRect(10, 50, 821, 441))
        self.tableWidgetAniversariantes.setObjectName("tableWidgetAniversariantes")
        self.tableWidgetAniversariantes.setColumnCount(0)
        self.tableWidgetAniversariantes.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aniversariantes"))
        self.labelData.setText(_translate("MainWindow", "Data de Aniversário:"))
        self.pushButtonPesquisar.setText(_translate("MainWindow", "PESQUISAR"))
