# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonBar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBar.setGeometry(QtCore.QRect(60, 10, 75, 23))
        self.pushButtonBar.setObjectName("pushButtonBar")
        self.tableWidgetSaldos = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetSaldos.setGeometry(QtCore.QRect(10, 50, 351, 461))
        self.tableWidgetSaldos.setObjectName("tableWidgetSaldos")
        self.tableWidgetSaldos.setColumnCount(0)
        self.tableWidgetSaldos.setRowCount(0)
        self.pushButtonCozinha = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCozinha.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.pushButtonCozinha.setObjectName("pushButtonCozinha")
        self.pushButtonImprimir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonImprimir.setGeometry(QtCore.QRect(140, 520, 75, 23))
        self.pushButtonImprimir.setObjectName("pushButtonImprimir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saldos de Estoque"))
        self.pushButtonBar.setText(_translate("MainWindow", "BAR"))
        self.pushButtonCozinha.setText(_translate("MainWindow", "COZINHA"))
        self.pushButtonImprimir.setText(_translate("MainWindow", "IMPRIMIR"))
